name: services
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to  1.0.0+1
# pub.dev using `flutter pub publish`. This is preferred for private packages.  >=3.2.0-134.0.dev <4.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev         >=3.5.0-131.0.dev <4.0.0

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  responsive_sizer: ^3.3.1
  image_picker: ^1.1.2
  video_player: ^2.8.7
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.3
  path: ^1.9.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  cloud_firestore: ^5.0.1
  firebase_database: ^11.0.1
  firebase_core: ^3.1.0
  fluttertoast: ^8.2.6
  navbar_router: ^0.7.4
  fluentui_system_icons: ^1.1.244
  curved_navigation_bar: ^1.0.6
  flutter_chat_ui: ^1.6.14
  uuid: ^4.4.0
  http: ^1.2.1
  open_filex: ^4.4.0
  file_picker: ^8.0.5
  mime: ^1.0.5
  like_button: ^2.0.5
  another_flushbar: ^1.12.30
  shared_preferences: ^2.2.3
  flutter_share: ^2.0.0
  babstrap_settings_screen: ^0.1.6
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/Logo.png
      - assets/camera.png
      - assets/gallery.png
  #    - assets/dummy.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
